BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ATV_RENTALS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ATV_TRAILS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ATV_INSTRUCTORS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ATV_FLEET CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ATV_CLIENTS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE atv_clients (
    client_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name      VARCHAR2(50) NOT NULL,
    last_name       VARCHAR2(50) NOT NULL,
    phone_number    VARCHAR2(20),
    email           VARCHAR2(100),
    date_of_birth   DATE,       
    driver_license  VARCHAR2(50),
    date_joined     DATE DEFAULT SYSDATE,
    
    CONSTRAINT pk_atv_clients PRIMARY KEY (client_id),
    CONSTRAINT uk_license UNIQUE (driver_license) 
);


CREATE TABLE atv_fleet (
    atv_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    model_name      VARCHAR2(100) NOT NULL, 
    brand           VARCHAR2(50),         
    status          VARCHAR2(20) CHECK (status IN ('Available', 'Broken', 'Rented')),
    daily_rate      NUMBER(10, 2),
    
    CONSTRAINT pk_atv_fleet PRIMARY KEY (atv_id)
);


CREATE TABLE atv_instructors (
    instructor_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name      VARCHAR2(50),
    last_name       VARCHAR2(50),
    hire_date       DATE DEFAULT SYSDATE,
    specialization  VARCHAR2(50),
    
    CONSTRAINT pk_atv_instructors PRIMARY KEY (instructor_id)
);

CREATE TABLE atv_trails (
    trail_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    trail_name      VARCHAR2(100) NOT NULL,
    difficulty      VARCHAR2(20) CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
    duration_hrs    NUMBER(4, 1),
    description     VARCHAR2(500),
    
    CONSTRAINT pk_atv_trails PRIMARY KEY (trail_id)
);

CREATE TABLE atv_rentals (
    client_id       NUMBER NOT NULL,
    atv_id          NUMBER NOT NULL,
    rental_date     DATE NOT NULL, 
    trail_id        NUMBER,
    instructor_id   NUMBER,
    price_paid      NUMBER(10, 2),

    CONSTRAINT pk_atv_rentals PRIMARY KEY (client_id, atv_id, rental_date),
    CONSTRAINT fk_rentals_client FOREIGN KEY (client_id) REFERENCES atv_clients(client_id),
    CONSTRAINT fk_rentals_atv    FOREIGN KEY (atv_id)    REFERENCES atv_fleet(atv_id),
    CONSTRAINT fk_rentals_trail  FOREIGN KEY (trail_id)  REFERENCES atv_trails(trail_id),
    CONSTRAINT fk_rentals_instr  FOREIGN KEY (instructor_id) REFERENCES atv_instructors(instructor_id)
);